### ISSUE TITLE
English translations for the FAQ

### ISSUE THREAD

**Issue by gkovacs** [zhanzhenzhen/futurescript#13]
I can translate your FAQ from Chinese to English if desired, just let me know where I should submit the pull request (the source of the FAQ page doesn't appear to be in this github repo). I've translated a few of them below:

问：为啥没有位操作符？
答：首先，FutureScript作为高级语言，没必要支持。其次，JavaScript的位操作是专门针对32位数字的，这本身就不合理。

Q: Why are there no bitwise operators?
A: First, FutureScript is a high-level language, so there is no need to support them. Second, JavaScript's bitwise operations are specifically targeted towards 32-bit numbers, which is unreasonable.

问：为啥没有保留字？
答：很多语言都有很多保留字，但我觉得你设计语言的时候预先定义好未来的功能，那未来有可能是你没料到的。我们在版本行使用版本号，也达到了“安全”的目的，因为可以保证只要你不修改版本号，就不会出现兼容性问题。

Q: Why are there no keywords reserved for future use?
A: Many languages have many reserved keywords, but I think that if you try to predict future features when you design the language, then you might not predict them correctly. In FutureScript, the version number achieves the goal of "safety", because so long as you do not change the version number, there will not be any compatibility issues.

问：保留旧版本的编译器，那岂不越来越庞大？好恐怖！
答：其实也没那么恐怖，我们在做FutureScript的时候会采取一些手段，使增量不那么大。

Q: If we keep versions of the compiler, won't it become increasingly large? Sounds scary!
A: Actually it's not that scary, while building FutureScript I adopted some techniques to ensure that the increase in size is not so large.

**Comment by zhanzhenzhen** [comment]
Thank you! Could you edit the `"spec/spec-en.xhtml"` file and submit a pull request?

**Comment by zhanzhenzhen** [comment]
Yes the source of the website is in another repo. But those files are the same. They are copied from this repo.

**Comment by gkovacs** [comment]
See https://github.com/zhanzhenzhen/futurescript/pull/14 for the first half (I'll do the remainder in another pull request once I have time)

**Comment by zhanzhenzhen** [comment]
Thank you! I have merged your commit. The rest are just a few paragraphs. I will do the remainder.

**Comment by zhanzhenzhen** [comment]
All are translated and copied to the website.
