### ISSUE TITLE
Using fus-ext with Node.js

### ISSUE THREAD

**Issue by kristianmandrup** [zhanzhenzhen/futurescript#15]
How do I use fus-ext in my project? I tried to follow your guide

`npm i -S fus-ext`

Copied *lodash* manifest file to my project root folder as `manifest.fus`. 
I also upgraded fus version from 2.2.0 to 2.4.0

```
fus 2.4.0
{
    loop
    repeat
    ....
}
```

My main file `first.fus`

```
fus 2.3.0
import "./manifest" all

loop(10, i ->
    console.log "This is \(i) time"
)
```

Compile works just fine, but running it gives strange output

```
19:57 $ fus c first.fus 
✔ ~/repos/futurejs-projs/abc 
19:58 $ node first.js 
/Users/kristianmandrup/repos/futurejs-projs/abc/first.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";import {loop as loop} from "./manifest";import {repeat as repeat} from "./manifest";import {break as var_573300145710716007_0} from "./manifest";import {enum as var_573300145710716007_1} from "./manifest";import {fail as fail} from "./manifest";import {compose as compose} from "./manifest";import {assert as assert} from "./manifest";import {spread as spread} from "./manifest";import {eventField as eventField} from "./manifest";import {setImmediate as setImmediate} from "./manifest";import {clearImmediate as clearImmediate} from "./manifest";import {Timer as Timer} from "./manifest";import {IntervalTimer as IntervalTimer} from "./manifest";import {Observer as Observer} from "./manifest";import {Point as Point} from "./manifest";import {sys as sys} from "./manifest";import {web as web} from "./manifest";import {cmath as cmath} from "./manifest";import {feNumber as feNumber} fro
SyntaxError: Unexpected token import
```

I'm on latest Node 7.7.1

Ah, this is because Node doesn't yet support import. 
Please allow for usage with Node.js as well using `require` instead. 
Cheers :) 

Ah, I found this hint:

_Here we used the "batch import" feature. Note that the export of manifest.fus should match the import of yours. If you want to use node instead of es, then you'll need to make corresponding changes in the version line of the two files._

However I can't seem to find any docs on how to set the version correctly to work with Node.
or  do I need to set up Babel for this to work?

Ah, now I found it on *version line* section of https://futurescript.org
Could be a little more clear. Please add this hint on fus-ext documentation site. 

`2.4.0, node modules`

Thanks!

 I now get:

```
20:13 $ cat first.js 
"use strict";var loop,repeat,fail,compose,assert,spread,eventField,setImmediate,clearImmediate,Timer,IntervalTimer,Observer,Point,sys,web,cmath,feNumber,feNumberStatic,feString,feObject,feArray,feMath,feJson,feDate,feConsole,feUint8Array,feUint8ArrayStatic,fePromiseStatic,dotDot_573300145710716007,global,var_573300145710716007_0,var_573300145710716007_1;loop=require("./manifest").loop;repeat=require("./manifest").repeat;var_573300145710716007_0=require("./manifest").break;var_573300145710716007_1=require("./manifest").enum;fail=require("./manifest").fail;compose=require("./manifest").compose;assert=require("./manifest").assert;spread=require("./manifest").spread
```

But there is no `manifest.js` file so I obviously get:

```
20:12 $ node first.js 
module.js:472
    throw err;
    ^

Error: Cannot find module './manifest'
```

Ah, so I need to compile the `manifest.fus` file as well ;)

**Comment by kristianmandrup** [comment]
Also tried compiling using `--map` for debug mode without luck

```
 $ fus c --map first.fus 
/usr/local/lib/node_modules/futurescript/target/bin.js:60
                throw ex;
                ^

TypeError: Cannot read property 'lex' of undefined
```

**Comment by kristianmandrup** [comment]
Finally sorted it out. I had to also edit the version part of `manifest.fus`
We need a generator of sorts to setup a basic project for either the client or server.
Will work on that next! Cheers :)

Please improve the docs a little on how to configure, step by step. 

```
$ fus c manifest.fus 
✔ ~/repos/futurejs-projs/abc 
20:17 $ node first.js
This is 0 time
```

**Comment by zhanzhenzhen** [comment]
You had edited both version lines of `manifest.fus` and your code file to `node modules`, so it's solved? OK, I'll improve the doc.

Is this sentence not very clear? "If you want to use node instead of es, then you'll need to make corresponding changes in the version line of the two files."

**Comment by zhanzhenzhen** [comment]
I myself am still using Babel so I have rarely used the `node modules` option. Is everything working fine?

**Comment by kristianmandrup** [comment]
Just feel the docs could be structured a little better. Node and ES compatibility and such should be at the top. Yes, works like a charm with Node.

Haven't studied the full docs yet. Wondering if you allow ruby method names ending in ? For Boolean checks such as: authorised? user

Reads in a much nicer way. You could also allow ! Postfix methods for those with side effects
