### ISSUE TITLE
Object implicit set key/value pair

### ISSUE THREAD

**Issue by kristianmandrup** [zhanzhenzhen/futurescript#24]
I tried the following:

```js
a: 1
b: "b"

x: {
  a,
  b
}  

console.log x
```

And got `{"a":true,"b":true}` when I would have like the ES6 equivalent `{a: 1,b: "b"}` is this really intended behaviour?

**Comment by zhanzhenzhen** [comment]
Yes, this is really the intended behavior. See Flexible Object section. The example 11 is related to that:
```
Color: enum{red, green, blue}
```
It compiles to `Color = enum({red: true, green: true, blue: true})`
