### ISSUE TITLE
Chinese characters in docs end of pattern matching section

### ISSUE THREAD

**Issue by kristianmandrup** [zhanzhenzhen/futurescript#28]
作为模式使用时要么全是or，要么全是and，两个不能在一个模式中一起出现，否则编译器会无法判断。括号内的无此限制。

注意or else是一种特殊的合并写法，并不属于or模式，所以or else可以和and一起出现。

???

**Comment by zhanzhenzhen** [comment]
Oh, didn't notice there's still something not translated.

**Comment by kristianmandrup** [comment]
I made a PR with fixes ;)

**Comment by zhanzhenzhen** [comment]
Fixed. Also, the font family is changed so the "details" sections are clearer.
